First pre-alpha complete version
Checks requirements better, generates a makefile.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 #Project Details
+NAME="project_name"
 MAIN="main.cc"
 USEBUILDDIR="yes"
 BUILDDIRNAME="build"
@@ -17,6 +18,7 @@ ccompilers=(gcc clang cc x86_64-mingw32-gcc i686-w64-mingw32-gcc)
 echo "CannonConfigure ./configure script, version $versionnumber"
 
 chosencompiler="errornocompile"
+compilersequence="errornocompile"
 
 for i in $cppcompilers
 do
@@ -34,8 +36,18 @@ if [ $chosencompiler = "errornocompile" ]; then
 	do
 		echo $i
 	done
+	exit
 else
 	echo -e "\033[32mFound $chosencompiler\033[m"
+fi
+
+echo -e "\033[33mChecking required source files...\033[m"
+if [[ -f $MAIN ]]; then
+	echo -e "\033[32mFound $MAIN.\033[m"
+else
+	echo -e "\007\033[1;31mSOURCE CODE ABSENT.\033[m"
+	echo "Please ensure that $MAIN exists and you have permissions to read it."
+	exit 1
 fi
 
 if [ $REQUIREINCLUDES = "yes" ]; then
@@ -44,11 +56,40 @@ if [ $REQUIREINCLUDES = "yes" ]; then
 		pkg-config $i
 		if [ $? = 0 ]; then
 			echo -e "Found $i"
+		else
+			echo -e "\007\033[31m$i NOT FOUND.\033[m"
+			echo "make sure all the associated libs are installed correctly."
 		fi
 	done
 fi
 
-echo -e "\007\033[1;32mConfigure complete.\033[m"
+if [ $USEBUILDDIR = "yes" ]; then
+	if [[ -d "$BUILDDIRNAME" ]]; then
+		echo -e "\033[32mWe have a build dir\033[m"
+	else
+		echo -e "\033[33mCreating build dir...\033[m"
+		mkdir "$BUILDDIRNAME"
+		if [[ -d "$BUILDDIRNAME" ]]; then
+			echo -e "\033[32mSUCCESS\033[m"
+		else
+			echo -e "\007\033[31mBUILD DIR CREATION FAILED!\033[m"
+			echo "make sure you have the proper permissions to access this folder."
+		fi
+	fi
+	cd "$BUILDDIRNAME"
+	MAIN="../$MAIN"
+fi
+
+compilersequence="$chosencompiler $MAIN -o $NAME"
+
+touch Makefile
+echo "$NAME: $MAIN
+	$compilersequence
+
+default: $MAIN
+	$compilersequence" > Makefile
+
+echo -e "\033[1;32mConfigure complete.\033[m"
 echo "You may now make the project. To do so, type: 
 "
 if [ $USEBUILDDIR = "yes" ]; then
